### ISSUE TITLE
копирование ключей не работает с КриптоПро CSP 3.9 и старее

### ISSUE THREAD

**Issue by cryptobro** [Patttern/CProGUI#3]
/opt/cprocsp/bin/amd64/csptest: unrecognized option `-contsrc'

**Comment by Patttern** [comment]
Не подразумевалась поддержка версий ниже 4.0, но для данной опции я добавлю изменения.
В разработке.

**Comment by Patttern** [comment]
Добавлено
https://github.com/Patttern/CProGUI/commit/bd0a0d1e1802f504224e024c5cacc42bb022eceb
